format_version: v1.0
type: UniqueComponent
attributes: {id: pmsm_foc}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: MCPMSMFOC_ADCPLIB}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: adchs}
  - type: Integer
    attributes: {id: MCPMSMFOC_ADC_DEP}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '1'}
  - type: Integer
    attributes: {id: MCPMSMFOC_ADC_MAX}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '4095'}
  - type: Float
    attributes: {id: MCPMSMFOC_CL_BANDWIDTH}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '2000.0'}
  - type: Integer
    attributes: {id: MCPMSMFOC_DCBUSV_CH}
    children:
    - type: Attributes
      children:
      - type: Integer
        attributes: {id: max}
        children:
        - {type: Value, value: '53'}
  - type: KeyValueSet
    attributes: {id: MCPMSMFOC_DIRECTION_BUTTON}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '30'}
  - type: KeyValueSet
    attributes: {id: MCPMSMFOC_DIRECTION_LED}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '59'}
  - type: KeyValueSet
    attributes: {id: MCPMSMFOC_FAULT_LED}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '77'}
  - type: Boolean
    attributes: {id: MCPMSMFOC_FLYING_START}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Float
    attributes: {id: MCPMSMFOC_FLYING_START_CL_BANDWIDTH}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '2000.0'}
  - type: Float
    attributes: {id: MCPMSMFOC_FLYING_START_ID_KI}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '9.9E-4'}
  - type: Float
    attributes: {id: MCPMSMFOC_FLYING_START_ID_KP}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '0.2'}
  - type: Float
    attributes: {id: MCPMSMFOC_FLYING_START_IQ_KI}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '9.9E-4'}
  - type: Float
    attributes: {id: MCPMSMFOC_FLYING_START_IQ_KP}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '0.2'}
  - type: Float
    attributes: {id: MCPMSMFOC_ID_KI}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '2.0E-4'}
  - type: Float
    attributes: {id: MCPMSMFOC_ID_KP}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '0.02'}
  - type: Boolean
    attributes: {id: MCPMSMFOC_INTERM_FLYING_START}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: 'false'}
  - type: Float
    attributes: {id: MCPMSMFOC_IQ_KI}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '2.0E-4'}
  - type: Float
    attributes: {id: MCPMSMFOC_IQ_KP}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '0.02'}
  - type: KeyValueSet
    attributes: {id: MCPMSMFOC_MOTOR_CONNECTION}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '0'}
  - type: Integer
    attributes: {id: MCPMSMFOC_PHASEU_CH}
    children:
    - type: Attributes
      children:
      - type: Integer
        attributes: {id: max}
        children:
        - {type: Value, value: '53'}
  - type: Integer
    attributes: {id: MCPMSMFOC_PHASEV_CH}
    children:
    - type: Attributes
      children:
      - type: Integer
        attributes: {id: max}
        children:
        - {type: Value, value: '53'}
  - type: Integer
    attributes: {id: MCPMSMFOC_POT_CH}
    children:
    - type: Attributes
      children:
      - type: Integer
        attributes: {id: max}
        children:
        - {type: Value, value: '53'}
  - type: String
    attributes: {id: MCPMSMFOC_PWMPLIB}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: mcpwm}
  - type: KeyValueSet
    attributes: {id: MCPMSMFOC_PWM_FAULT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '14'}
  - type: Integer
    attributes: {id: MCPMSMFOC_PWM_PH_U}
    children:
    - type: Attributes
      children:
      - type: Integer
        attributes: {id: max}
        children:
        - {type: Value, value: '11'}
  - type: Integer
    attributes: {id: MCPMSMFOC_PWM_PH_V}
    children:
    - type: Attributes
      children:
      - type: Integer
        attributes: {id: max}
        children:
        - {type: Value, value: '11'}
  - type: Integer
    attributes: {id: MCPMSMFOC_PWM_PH_W}
    children:
    - type: Attributes
      children:
      - type: Integer
        attributes: {id: max}
        children:
        - {type: Value, value: '11'}
  - type: KeyValueSet
    attributes: {id: MCPMSMFOC_START_BUTTON}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '67'}
  - type: String
    attributes: {id: MCPMSMFOC_X2CScope}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: X2CScope}
- type: Attachments
  children:
  - type: MultiCapability
    attributes: {id: pmsmfoc_ADC}
    children:
    - type: TargetAttachments
      children:
      - type: TargetAttachment
        attributes: {targetComponentID: adchs, targetAttachmentID: ADCHS_ADC}
  - type: DirectDependency
    attributes: {id: pmsmfoc_PWM}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: mcpwm}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: MCPWM_PWM}
  - type: DirectDependency
    attributes: {id: pmsmfoc_X2CSCOPE}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: X2CScope}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: x2cScope_Scope}
- type: ElementPosition
  attributes: {x: '454', y: '118', id: pmsm_foc}
