format_version: v1.0
type: UniqueComponent
attributes: {id: pmsm_foc}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: MCPMSMFOC_ADC_MODULE_01}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: adchs}
  - type: Combo
    attributes: {id: MCPMSMFOC_BUS_VOLTAGE_VDC_UNIT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: ADC7}
  - type: Combo
    attributes: {id: MCPMSMFOC_BUS_VOLTAGE_VDC_UNIT_BUS_VOLTAGE_VDC_ADC7}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: Channel 14}
  - type: String
    attributes: {id: MCPMSMFOC_BUS_VOLTAGE_VDC_UNIT_BUS_VOLTAGE_VDC_FINAL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '14'}
  - type: Integer
    attributes: {id: MCPMSMFOC_BUTTONS_AVAILABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '2'}
  - type: String
    attributes: {id: MCPMSMFOC_BUTTON_0_NAME}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: BUTTON_01}
  - type: Combo
    attributes: {id: MCPMSMFOC_BUTTON_0_NUMBER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: RA12}
  - type: String
    attributes: {id: MCPMSMFOC_BUTTON_1_NAME}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: BUTTON_02}
  - type: Combo
    attributes: {id: MCPMSMFOC_BUTTON_1_NUMBER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: RC13}
  - type: Combo
    attributes: {id: MCPMSMFOC_ENCODER_PERIPHERAL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: QEI1}
  - type: String
    attributes: {id: MCPMSMFOC_ENCODER_PERIPHERAL_QEA_FINAL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '1'}
  - type: String
    attributes: {id: MCPMSMFOC_ENCODER_PERIPHERAL_QEB_FINAL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '1'}
  - type: Float
    attributes: {id: MCPMSMFOC_ID_PID_KP}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0.02'}
  - type: Float
    attributes: {id: MCPMSMFOC_IQ_PID_KP}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0.02'}
  - type: Integer
    attributes: {id: MCPMSMFOC_LEDS_AVAILABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '2'}
  - type: String
    attributes: {id: MCPMSMFOC_LED_0_NAME}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: LED_01}
  - type: Combo
    attributes: {id: MCPMSMFOC_LED_0_NUMBER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: RD8}
  - type: String
    attributes: {id: MCPMSMFOC_LED_1_NAME}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: LED_02}
  - type: Combo
    attributes: {id: MCPMSMFOC_LED_1_NUMBER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: RA7}
  - type: KeyValueSet
    attributes: {id: MCPMSMFOC_MOTOR_CONNECTION}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '0'}
  - type: Combo
    attributes: {id: MCPMSMFOC_PHASE_CURRENT_IA_UNIT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: ADC0}
  - type: Combo
    attributes: {id: MCPMSMFOC_PHASE_CURRENT_IA_UNIT_PHASE_CURRENT_IA_ADC0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: Channel 13}
  - type: String
    attributes: {id: MCPMSMFOC_PHASE_CURRENT_IA_UNIT_PHASE_CURRENT_IA_FINAL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '13'}
  - type: Combo
    attributes: {id: MCPMSMFOC_PHASE_CURRENT_IB_UNIT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: ADC1}
  - type: Combo
    attributes: {id: MCPMSMFOC_PHASE_CURRENT_IB_UNIT_PHASE_CURRENT_IB_ADC1}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: Channel 16}
  - type: String
    attributes: {id: MCPMSMFOC_PHASE_CURRENT_IB_UNIT_PHASE_CURRENT_IB_FINAL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '16'}
  - type: Combo
    attributes: {id: MCPMSMFOC_POTENTIOMETER_VPOT_UNIT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: ADC7}
  - type: Combo
    attributes: {id: MCPMSMFOC_POTENTIOMETER_VPOT_UNIT_POTENTIOMETER_VPOT_ADC7}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: Channel 15}
  - type: String
    attributes: {id: MCPMSMFOC_POTENTIOMETER_VPOT_UNIT_POTENTIOMETER_VPOT_FINAL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '15'}
  - type: String
    attributes: {id: MCPMSMFOC_PWMPLIB}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: mcpwm}
  - type: Combo
    attributes: {id: MCPMSMFOC_PWM_INSTANCE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: MCPWM}
  - type: String
    attributes: {id: MCPMSMFOC_PWM_INSTANCE_PWM_A_FINAL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '1'}
  - type: String
    attributes: {id: MCPMSMFOC_PWM_INSTANCE_PWM_B_FINAL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '2'}
  - type: String
    attributes: {id: MCPMSMFOC_PWM_INSTANCE_PWM_C_FINAL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '3'}
  - type: String
    attributes: {id: MCPMSMFOC_X2CScope}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: X2CScope}
- type: Attachments
  children:
  - type: MultiCapability
    attributes: {id: pmsmfoc_ADC}
    children:
    - type: TargetAttachments
      children:
      - type: TargetAttachment
        attributes: {targetComponentID: adchs, targetAttachmentID: ADCHS_ADC}
  - type: DirectDependency
    attributes: {id: pmsmfoc_PWM}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: mcpwm}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: MCPWM_PWM}
  - type: DirectDependency
    attributes: {id: pmsmfoc_QDEC}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: DirectDependency
    attributes: {id: pmsmfoc_X2CSCOPE}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: X2CScope}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: x2cScope_Scope}
- type: ElementPosition
  attributes: {x: '328', y: '214', id: pmsm_foc}
