package:
  format-version: "1.0.0"
  name: "mc_apps_pic32mk"
  version: "v3.4.1"
  type: "application"
  status: "production"
  required: false

  dependencies:
    - name: "motor_control"
      type: "package"
      version: "v3.10.1"