files:
- generatedChecksum: DBEB484D45D924F226145E41226877FB
  logicalPath: config\mclv2_pic32_mk_mcm_pim\X2CCode\X2CScope
  name: X2CScope.c
  physicalPath: X2CCode\X2CScope\src
  security: NON_SECURE
  type: SOURCE
  userChecksum: DBEB484D45D924F226145E41226877FB
- generatedChecksum: 8B8EDEA47D6019608B1C479D3DA3B114
  logicalPath: config\mclv2_pic32_mk_mcm_pim\X2CCode\X2CScope
  name: X2CScopeCommunication.c
  physicalPath: X2CCode\X2CScope\src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 8B8EDEA47D6019608B1C479D3DA3B114
- generatedChecksum: C2B88D9215301ECE3DC36E4B82F2791C
  logicalPath: config\mclv2_pic32_mk_mcm_pim
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: C2B88D9215301ECE3DC36E4B82F2791C
- generatedChecksum: 7470167A5FFD4F171C6E4EF197AB1C5C
  logicalPath: config\mclv2_pic32_mk_mcm_pim
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7470167A5FFD4F171C6E4EF197AB1C5C
- generatedChecksum: 7EFD9E3C27BB84C505A9EC7173A83AD7
  logicalPath: config\mclv2_pic32_mk_mcm_pim
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7EFD9E3C27BB84C505A9EC7173A83AD7
- generatedChecksum: null
  logicalPath: ''
  name: main_mclv2.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: DCCECAB4A225A35D581B34E8818935C7
  logicalPath: config\mclv2_pic32_mk_mcm_pim\motor_control\pmsm_foc
  name: mc_control_loop.c
  physicalPath: motor_control\pmsm_foc
  security: NON_SECURE
  type: SOURCE
  userChecksum: DCCECAB4A225A35D581B34E8818935C7
- generatedChecksum: C72E5BF09658C7E8E0866749A9806FAD
  logicalPath: config\mclv2_pic32_mk_mcm_pim\motor_control\pmsm_foc
  name: mc_currmeasurement.c
  physicalPath: motor_control\pmsm_foc
  security: NON_SECURE
  type: SOURCE
  userChecksum: C72E5BF09658C7E8E0866749A9806FAD
- generatedChecksum: 030A53782FE4339B2A528B9E2E8779A6
  logicalPath: config\mclv2_pic32_mk_mcm_pim\motor_control\pmsm_foc
  name: mc_errorhandler.c
  physicalPath: motor_control\pmsm_foc
  security: NON_SECURE
  type: SOURCE
  userChecksum: 030A53782FE4339B2A528B9E2E8779A6
- generatedChecksum: E57D238B7F022F210CE69D989AB3730E
  logicalPath: config\mclv2_pic32_mk_mcm_pim\motor_control\pmsm_foc
  name: mc_generic_lib.c
  physicalPath: motor_control\pmsm_foc
  security: NON_SECURE
  type: SOURCE
  userChecksum: E57D238B7F022F210CE69D989AB3730E
- generatedChecksum: 046470AD5272DEB5B219C3783E57A081
  logicalPath: config\mclv2_pic32_mk_mcm_pim\motor_control\pmsm_foc
  name: mc_lib.c
  physicalPath: motor_control\pmsm_foc
  security: NON_SECURE
  type: SOURCE
  userChecksum: 046470AD5272DEB5B219C3783E57A081
- generatedChecksum: DB974AE28FF3C709864895902C80709A
  logicalPath: config\mclv2_pic32_mk_mcm_pim\motor_control\pmsm_foc
  name: mc_picontrol.c
  physicalPath: motor_control\pmsm_foc
  security: NON_SECURE
  type: SOURCE
  userChecksum: DB974AE28FF3C709864895902C80709A
- generatedChecksum: D5CECF6FD94EAEF793BA0E124E6AF6A9
  logicalPath: config\mclv2_pic32_mk_mcm_pim\motor_control\pmsm_foc
  name: mc_pmsm_foc.c
  physicalPath: motor_control\pmsm_foc
  security: NON_SECURE
  type: SOURCE
  userChecksum: D5CECF6FD94EAEF793BA0E124E6AF6A9
- generatedChecksum: 4D909A989ADD6A5A7EF0ECA93F19FAAE
  logicalPath: config\mclv2_pic32_mk_mcm_pim\motor_control\pmsm_foc
  name: mc_pwm.c
  physicalPath: motor_control\pmsm_foc
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4D909A989ADD6A5A7EF0ECA93F19FAAE
- generatedChecksum: ABAABC1CE5EFDE16363B13CD8AAD1A76
  logicalPath: config\mclv2_pic32_mk_mcm_pim\motor_control\pmsm_foc
  name: mc_rotorposition.c
  physicalPath: motor_control\pmsm_foc
  security: NON_SECURE
  type: SOURCE
  userChecksum: ABAABC1CE5EFDE16363B13CD8AAD1A76
- generatedChecksum: 36BF8996C103287DB7B0A62CEFF16EB7
  logicalPath: config\mclv2_pic32_mk_mcm_pim\motor_control\pmsm_foc
  name: mc_speed.c
  physicalPath: motor_control\pmsm_foc
  security: NON_SECURE
  type: SOURCE
  userChecksum: 36BF8996C103287DB7B0A62CEFF16EB7
- generatedChecksum: AC6BCEE3FBA8DE5023D13C3EB1EA76A0
  logicalPath: config\mclv2_pic32_mk_mcm_pim\motor_control\pmsm_foc
  name: mc_voltagemeasurement.c
  physicalPath: motor_control\pmsm_foc
  security: NON_SECURE
  type: SOURCE
  userChecksum: AC6BCEE3FBA8DE5023D13C3EB1EA76A0
- generatedChecksum: A11AD61211395ADD6ABFC381B067F8DB
  logicalPath: config\mclv2_pic32_mk_mcm_pim\peripheral\adchs
  name: plib_adchs.c
  physicalPath: peripheral\adchs
  security: NON_SECURE
  type: SOURCE
  userChecksum: A11AD61211395ADD6ABFC381B067F8DB
- generatedChecksum: FD6E3BDDF3F83133EBEEC335F2D4D64B
  logicalPath: config\mclv2_pic32_mk_mcm_pim\peripheral\clk
  name: plib_clk.c
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: FD6E3BDDF3F83133EBEEC335F2D4D64B
- generatedChecksum: 16FF4D54461CA628FC86D6C5667909E4
  logicalPath: config\mclv2_pic32_mk_mcm_pim\peripheral\evic
  name: plib_evic.c
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 16FF4D54461CA628FC86D6C5667909E4
- generatedChecksum: 6F20675676C74ABDA2DDF672A6D116B1
  logicalPath: config\mclv2_pic32_mk_mcm_pim\peripheral\gpio
  name: plib_gpio.c
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 6F20675676C74ABDA2DDF672A6D116B1
- generatedChecksum: 14EC08B2B2233854BC4CDD8F98BA1892
  logicalPath: config\mclv2_pic32_mk_mcm_pim\peripheral\mcpwm
  name: plib_mcpwm.c
  physicalPath: peripheral\mcpwm
  security: NON_SECURE
  type: SOURCE
  userChecksum: 14EC08B2B2233854BC4CDD8F98BA1892
- generatedChecksum: 31E61629E04490FBFB0ADD0234733309
  logicalPath: config\mclv2_pic32_mk_mcm_pim\peripheral\uart
  name: plib_uart2.c
  physicalPath: peripheral\uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 31E61629E04490FBFB0ADD0234733309
- generatedChecksum: 16BE5CCEE5F9AF5909BF3F69B51C7D93
  logicalPath: config\mclv2_pic32_mk_mcm_pim\stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 16BE5CCEE5F9AF5909BF3F69B51C7D93
- generatedChecksum: 5591C3627E1EAF04874E2BAA428546AB
  logicalPath: config\mclv2_pic32_mk_mcm_pim\X2CCode\X2CScope
  name: X2CScope.h
  physicalPath: X2CCode\X2CScope\inc
  security: NON_SECURE
  type: HEADER
  userChecksum: 5591C3627E1EAF04874E2BAA428546AB
- generatedChecksum: CA44DEA5CA47431DCFE19A280CE9644A
  logicalPath: config\mclv2_pic32_mk_mcm_pim\X2CCode\X2CScope
  name: X2CScopeCommunication.h
  physicalPath: X2CCode\X2CScope\inc
  security: NON_SECURE
  type: HEADER
  userChecksum: CA44DEA5CA47431DCFE19A280CE9644A
- generatedChecksum: 75977A2C00C5A32DBE160AB57F57134B
  logicalPath: config\mclv2_pic32_mk_mcm_pim
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 75977A2C00C5A32DBE160AB57F57134B
- generatedChecksum: 5D5C52527AB1435153DB9B50ADE6B79D
  logicalPath: config\mclv2_pic32_mk_mcm_pim
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 5D5C52527AB1435153DB9B50ADE6B79D
- generatedChecksum: E75DF0D090D18FD603E217071A221A77
  logicalPath: config\mclv2_pic32_mk_mcm_pim\motor_control\pmsm_foc
  name: mc_control_loop.h
  physicalPath: motor_control\pmsm_foc
  security: NON_SECURE
  type: HEADER
  userChecksum: E75DF0D090D18FD603E217071A221A77
- generatedChecksum: CF0D0D9364EE61213CCA9BE75D92B9C3
  logicalPath: config\mclv2_pic32_mk_mcm_pim\motor_control\pmsm_foc
  name: mc_currmeasurement.h
  physicalPath: motor_control\pmsm_foc
  security: NON_SECURE
  type: HEADER
  userChecksum: CF0D0D9364EE61213CCA9BE75D92B9C3
- generatedChecksum: 6481453B07380DA8C20173D2A1113474
  logicalPath: config\mclv2_pic32_mk_mcm_pim\motor_control\pmsm_foc
  name: mc_derivedparams.h
  physicalPath: motor_control\pmsm_foc
  security: NON_SECURE
  type: HEADER
  userChecksum: 6481453B07380DA8C20173D2A1113474
- generatedChecksum: 22ADBB46B4B767FC49BA2C1F0D039727
  logicalPath: config\mclv2_pic32_mk_mcm_pim\motor_control\pmsm_foc
  name: mc_errorhandler.h
  physicalPath: motor_control\pmsm_foc
  security: NON_SECURE
  type: HEADER
  userChecksum: 22ADBB46B4B767FC49BA2C1F0D039727
- generatedChecksum: BE619BF7219A4C0A4155D16D53073C45
  logicalPath: config\mclv2_pic32_mk_mcm_pim\motor_control\pmsm_foc
  name: mc_generic_lib.h
  physicalPath: motor_control\pmsm_foc
  security: NON_SECURE
  type: HEADER
  userChecksum: BE619BF7219A4C0A4155D16D53073C45
- generatedChecksum: DD348633998BD3EE8A02D062DF00E874
  logicalPath: config\mclv2_pic32_mk_mcm_pim\motor_control\pmsm_foc
  name: mc_hal.h
  physicalPath: motor_control\pmsm_foc
  security: NON_SECURE
  type: HEADER
  userChecksum: DD348633998BD3EE8A02D062DF00E874
- generatedChecksum: E1CF71AE8C891A0CC5E7DE38C6F8A130
  logicalPath: config\mclv2_pic32_mk_mcm_pim\motor_control\pmsm_foc
  name: mc_lib.h
  physicalPath: motor_control\pmsm_foc
  security: NON_SECURE
  type: HEADER
  userChecksum: E1CF71AE8C891A0CC5E7DE38C6F8A130
- generatedChecksum: 25A5AB582A61262F42B2CA47E12163BC
  logicalPath: config\mclv2_pic32_mk_mcm_pim\motor_control\pmsm_foc
  name: mc_picontrol.h
  physicalPath: motor_control\pmsm_foc
  security: NON_SECURE
  type: HEADER
  userChecksum: 25A5AB582A61262F42B2CA47E12163BC
- generatedChecksum: 7926A8F2E6252633399B209881C6BFFD
  logicalPath: config\mclv2_pic32_mk_mcm_pim\motor_control\pmsm_foc
  name: mc_pmsm_foc.h
  physicalPath: motor_control\pmsm_foc
  security: NON_SECURE
  type: HEADER
  userChecksum: 7926A8F2E6252633399B209881C6BFFD
- generatedChecksum: 5FAD54D8E02B7E6C608149A7ACA45D53
  logicalPath: config\mclv2_pic32_mk_mcm_pim\motor_control\pmsm_foc
  name: mc_pmsm_foc_common.h
  physicalPath: motor_control\pmsm_foc
  security: NON_SECURE
  type: HEADER
  userChecksum: 5FAD54D8E02B7E6C608149A7ACA45D53
- generatedChecksum: FC4DB07EE52EE9E6D50B06C904709C1B
  logicalPath: config\mclv2_pic32_mk_mcm_pim\motor_control\pmsm_foc
  name: mc_pwm.h
  physicalPath: motor_control\pmsm_foc
  security: NON_SECURE
  type: HEADER
  userChecksum: FC4DB07EE52EE9E6D50B06C904709C1B
- generatedChecksum: 7E5EBB1A36DFE00353656F950EE535F7
  logicalPath: config\mclv2_pic32_mk_mcm_pim\motor_control\pmsm_foc
  name: mc_rotorposition.h
  physicalPath: motor_control\pmsm_foc
  security: NON_SECURE
  type: HEADER
  userChecksum: 7E5EBB1A36DFE00353656F950EE535F7
- generatedChecksum: 961A9231A4979273856BB1654A78E519
  logicalPath: config\mclv2_pic32_mk_mcm_pim\motor_control\pmsm_foc
  name: mc_speed.h
  physicalPath: motor_control\pmsm_foc
  security: NON_SECURE
  type: HEADER
  userChecksum: 961A9231A4979273856BB1654A78E519
- generatedChecksum: C4C3E3725825502BF1256B71B09738AC
  logicalPath: config\mclv2_pic32_mk_mcm_pim\motor_control\pmsm_foc
  name: mc_userparams.h
  physicalPath: motor_control\pmsm_foc
  security: NON_SECURE
  type: HEADER
  userChecksum: C4C3E3725825502BF1256B71B09738AC
- generatedChecksum: 8AFE5CA5C018707864411FDEAF49C650
  logicalPath: config\mclv2_pic32_mk_mcm_pim\motor_control\pmsm_foc
  name: mc_voltagemeasurement.h
  physicalPath: motor_control\pmsm_foc
  security: NON_SECURE
  type: HEADER
  userChecksum: 8AFE5CA5C018707864411FDEAF49C650
- generatedChecksum: 74058744638925EEB20F58B4328F1B68
  logicalPath: config\mclv2_pic32_mk_mcm_pim\peripheral\adchs
  name: plib_adchs.h
  physicalPath: peripheral\adchs
  security: NON_SECURE
  type: HEADER
  userChecksum: 74058744638925EEB20F58B4328F1B68
- generatedChecksum: 5485BB926F2ECC7BD1D7B2DE51ED2795
  logicalPath: config\mclv2_pic32_mk_mcm_pim\peripheral\adchs
  name: plib_adchs_common.h
  physicalPath: peripheral\adchs
  security: NON_SECURE
  type: HEADER
  userChecksum: 5485BB926F2ECC7BD1D7B2DE51ED2795
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config\mclv2_pic32_mk_mcm_pim\peripheral\clk
  name: plib_clk.h
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: D270E1FFFF82CBEE613690DC9636B8F9
  logicalPath: config\mclv2_pic32_mk_mcm_pim\peripheral\evic
  name: plib_evic.h
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: HEADER
  userChecksum: D270E1FFFF82CBEE613690DC9636B8F9
- generatedChecksum: 21A7B3C83BE7ED10FDDEF07C8FE9D141
  logicalPath: config\mclv2_pic32_mk_mcm_pim\peripheral\gpio
  name: plib_gpio.h
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 21A7B3C83BE7ED10FDDEF07C8FE9D141
- generatedChecksum: 12CBE2439F4C4DECD2B376033BBADA45
  logicalPath: config\mclv2_pic32_mk_mcm_pim\peripheral\mcpwm
  name: plib_mcpwm.h
  physicalPath: peripheral\mcpwm
  security: NON_SECURE
  type: HEADER
  userChecksum: 12CBE2439F4C4DECD2B376033BBADA45
- generatedChecksum: 8C0682DB8DD38F7C09771C63347D06FF
  logicalPath: config\mclv2_pic32_mk_mcm_pim\peripheral\mcpwm
  name: plib_mcpwm_common.h
  physicalPath: peripheral\mcpwm
  security: NON_SECURE
  type: HEADER
  userChecksum: 8C0682DB8DD38F7C09771C63347D06FF
- generatedChecksum: 687F99E456839E29578ACB606A2A0083
  logicalPath: config\mclv2_pic32_mk_mcm_pim\peripheral\uart
  name: plib_uart2.h
  physicalPath: peripheral\uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 687F99E456839E29578ACB606A2A0083
- generatedChecksum: CB4B34D1ABCE74BF62A89A7FF936BE91
  logicalPath: config\mclv2_pic32_mk_mcm_pim\peripheral\uart
  name: plib_uart_common.h
  physicalPath: peripheral\uart
  security: NON_SECURE
  type: HEADER
  userChecksum: CB4B34D1ABCE74BF62A89A7FF936BE91
- generatedChecksum: 2C8543317B3F067432097AB9BD3E8672
  logicalPath: config\mclv2_pic32_mk_mcm_pim
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 2C8543317B3F067432097AB9BD3E8672
- generatedChecksum: 4E94809C0DA4961DBBC8AA123A67CBF0
  logicalPath: config\mclv2_pic32_mk_mcm_pim
  name: p32MK1024MCM100.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 4E94809C0DA4961DBBC8AA123A67CBF0
format_version: v1.0
libraries:
- name: libPIC32MK_X2CScope.a
  path: /X2CCode/X2CScope/lib/
  security: NON_SECURE
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src/config/mclv2_pic32_mk_mcm_pim/X2CCode
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/mclv2_pic32_mk_mcm_pim;../src/packs/PIC32MK1024MCM100_DFP;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/mclv2_pic32_mk_mcm_pim;../src/packs/PIC32MK1024MCM100_DFP;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
