configName: mclv2_pic32_mk_mcm_pim
folderName: ''
format_version: v1.0
frameworkPath: ../../..
processor: PIC32MK1024MCM100
projectName: ''
settings:
  PackageFilter: csp;csp_apps_pic32mk;csp_apps_sam_d5x_e5x;csp_apps_sam_e70_s70_v70_v71;mc_apps_pic32mk;mc_apps_sam_c2x;mc_apps_sam_d5x_e5x;mc_apps_sam_e7x_s7x_v7x;motor_control;x2c
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32MK-MC_DFP\1.6.125\atdf\PIC32MK1024MCM100.atdf
