format_version: v1.0
type: UniqueComponent
attributes: {id: BSP_PIC32MK_MCM_PIM_MC_Board, bsp: 'true'}
children:
- type: ElementPosition
  attributes: {x: '94', y: '499', id: BSP_PIC32MK_MCM_PIM_MC_Board}
