files:
- generatedChecksum: DBEB484D45D924F226145E41226877FB
  logicalPath: config/mchv3_pic32_mk_mcm_pim/X2CCode/X2CScope
  name: X2CScope.c
  physicalPath: X2CCode/X2CScope/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: DBEB484D45D924F226145E41226877FB
- generatedChecksum: 8B8EDEA47D6019608B1C479D3DA3B114
  logicalPath: config/mchv3_pic32_mk_mcm_pim/X2CCode/X2CScope
  name: X2CScopeCommunication.c
  physicalPath: X2CCode/X2CScope/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 8B8EDEA47D6019608B1C479D3DA3B114
- generatedChecksum: 2F6CC050E57B9E5BA8A6C6C9A2D8F09A
  logicalPath: config/mchv3_pic32_mk_mcm_pim/bsp
  name: bsp.c
  physicalPath: bsp
  security: NON_SECURE
  type: SOURCE
  userChecksum: 2F6CC050E57B9E5BA8A6C6C9A2D8F09A
- generatedChecksum: 99DB74296DF9943C474F4F03A700C790
  logicalPath: config/mchv3_pic32_mk_mcm_pim
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 99DB74296DF9943C474F4F03A700C790
- generatedChecksum: 0248BC7DDDA019C67926A77FC9F09E16
  logicalPath: config/mchv3_pic32_mk_mcm_pim
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 0248BC7DDDA019C67926A77FC9F09E16
- generatedChecksum: B0F39798B30094FBB5DB9885FA092D95
  logicalPath: config/mchv3_pic32_mk_mcm_pim
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: B0F39798B30094FBB5DB9885FA092D95
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 9ED9B589DCF5759C4AE8D01844964040
  logicalPath: config/mchv3_pic32_mk_mcm_pim/motor_control/pmsm_foc
  name: mc_current_calculation.c
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: SOURCE
  userChecksum: 9ED9B589DCF5759C4AE8D01844964040
- generatedChecksum: 3601868C00DC28C75156590387BA6A84
  logicalPath: config/mchv3_pic32_mk_mcm_pim/motor_control/pmsm_foc
  name: mc_current_control.c
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: SOURCE
  userChecksum: 3601868C00DC28C75156590387BA6A84
- generatedChecksum: 5BF6505AB140C800F875CE33A240DC60
  logicalPath: config/mchv3_pic32_mk_mcm_pim/motor_control/pmsm_foc
  name: mc_error_handler.c
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: SOURCE
  userChecksum: 5BF6505AB140C800F875CE33A240DC60
- generatedChecksum: D50D356D7402349450EA64AB58779CD7
  logicalPath: config/mchv3_pic32_mk_mcm_pim/motor_control/pmsm_foc
  name: mc_flux_control.c
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: SOURCE
  userChecksum: D50D356D7402349450EA64AB58779CD7
- generatedChecksum: 2CCE8E5F8013E2EFDA2F6FC79F34FEFA
  logicalPath: config/mchv3_pic32_mk_mcm_pim/motor_control/pmsm_foc
  name: mc_flying_start.c
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: SOURCE
  userChecksum: 2CCE8E5F8013E2EFDA2F6FC79F34FEFA
- generatedChecksum: 33A5BAF3E6005EE8945FF36B32851036
  logicalPath: config/mchv3_pic32_mk_mcm_pim/motor_control/pmsm_foc
  name: mc_function_coordinator.c
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: SOURCE
  userChecksum: 33A5BAF3E6005EE8945FF36B32851036
- generatedChecksum: 484F511BDCA24F5374EFC2B1DDAA8CCF
  logicalPath: config/mchv3_pic32_mk_mcm_pim/motor_control/pmsm_foc
  name: mc_generic_library.c
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: SOURCE
  userChecksum: 484F511BDCA24F5374EFC2B1DDAA8CCF
- generatedChecksum: 428601C1E7B3667EB9DB623FB48B0AE1
  logicalPath: config/mchv3_pic32_mk_mcm_pim/motor_control/pmsm_foc
  name: mc_hardware_abstraction.c
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: SOURCE
  userChecksum: 428601C1E7B3667EB9DB623FB48B0AE1
- generatedChecksum: 88E65F06055CE2C04C33B5AE96A984C9
  logicalPath: config/mchv3_pic32_mk_mcm_pim/motor_control/pmsm_foc
  name: mc_interface_handling.c
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: SOURCE
  userChecksum: 88E65F06055CE2C04C33B5AE96A984C9
- generatedChecksum: B7F2BA687A398DDD5964911C30458280
  logicalPath: config/mchv3_pic32_mk_mcm_pim/motor_control/pmsm_foc
  name: mc_motor_control.c
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: SOURCE
  userChecksum: EAA80DD40EAD6EC4ADD78E6A3DD9B42B
- generatedChecksum: 713B191884A77E5402B7DD70FA0677BB
  logicalPath: config/mchv3_pic32_mk_mcm_pim/motor_control/pmsm_foc
  name: mc_pmsm_foc.c
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: SOURCE
  userChecksum: 713B191884A77E5402B7DD70FA0677BB
- generatedChecksum: 2337846FBCA5C415C4286B488D58BF83
  logicalPath: config/mchv3_pic32_mk_mcm_pim/motor_control/pmsm_foc
  name: mc_position_control.c
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: SOURCE
  userChecksum: 2337846FBCA5C415C4286B488D58BF83
- generatedChecksum: A913561E1120E5A256A1858BAFC9B0BE
  logicalPath: config/mchv3_pic32_mk_mcm_pim/motor_control/pmsm_foc
  name: mc_pwm.c
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: SOURCE
  userChecksum: A913561E1120E5A256A1858BAFC9B0BE
- generatedChecksum: ABAC8ACF6A85B28A42FA852F02319B96
  logicalPath: config/mchv3_pic32_mk_mcm_pim/motor_control/pmsm_foc
  name: mc_ramp_profiler.c
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: SOURCE
  userChecksum: ABAC8ACF6A85B28A42FA852F02319B96
- generatedChecksum: 5F7E54206070480A0948DB7A164C4DB7
  logicalPath: config/mchv3_pic32_mk_mcm_pim/motor_control/pmsm_foc
  name: mc_rotor_position.c
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: SOURCE
  userChecksum: 5F7E54206070480A0948DB7A164C4DB7
- generatedChecksum: C5798136A077E54FAE20F9A3430462CC
  logicalPath: config/mchv3_pic32_mk_mcm_pim/motor_control/pmsm_foc
  name: mc_speed_control.c
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: SOURCE
  userChecksum: C5798136A077E54FAE20F9A3430462CC
- generatedChecksum: 78195C4CEDD2D199633825C5AEA6A3C1
  logicalPath: config/mchv3_pic32_mk_mcm_pim/motor_control/pmsm_foc
  name: mc_start_up.c
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: SOURCE
  userChecksum: 78195C4CEDD2D199633825C5AEA6A3C1
- generatedChecksum: 8F52BE5B73F0514958B4B7C1B7163260
  logicalPath: config/mchv3_pic32_mk_mcm_pim/motor_control/pmsm_foc
  name: mc_voltage_measurement.c
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: SOURCE
  userChecksum: 8F52BE5B73F0514958B4B7C1B7163260
- generatedChecksum: 11A2A98526D07A8AF2D256ED566DEC03
  logicalPath: config/mchv3_pic32_mk_mcm_pim/peripheral/adchs
  name: plib_adchs.c
  physicalPath: peripheral/adchs
  security: NON_SECURE
  type: SOURCE
  userChecksum: 26ADB32EEE970A354E92E927AB9D3D34
- generatedChecksum: B0C89B568F77FAFD335FBB3F0FC1E2AE
  logicalPath: config/mchv3_pic32_mk_mcm_pim/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: B0C89B568F77FAFD335FBB3F0FC1E2AE
- generatedChecksum: 7CB282FCDBD6BAEE0A366A720C399BB5
  logicalPath: config/mchv3_pic32_mk_mcm_pim/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7CB282FCDBD6BAEE0A366A720C399BB5
- generatedChecksum: 79BB022878FC950B8AB96BDE84AC85DF
  logicalPath: config/mchv3_pic32_mk_mcm_pim/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 79BB022878FC950B8AB96BDE84AC85DF
- generatedChecksum: B959D8E5B714073329B6D1F97D77F793
  logicalPath: config/mchv3_pic32_mk_mcm_pim/peripheral/mcpwm
  name: plib_mcpwm.c
  physicalPath: peripheral/mcpwm
  security: NON_SECURE
  type: SOURCE
  userChecksum: B959D8E5B714073329B6D1F97D77F793
- generatedChecksum: 3BCCAC74DA905CB7A25EB40416F30A6D
  logicalPath: config/mchv3_pic32_mk_mcm_pim/peripheral/uart
  name: plib_uart2.c
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 3BCCAC74DA905CB7A25EB40416F30A6D
- generatedChecksum: 71352EF41F6688AD8408E42970B50B66
  logicalPath: config/mchv3_pic32_mk_mcm_pim/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 71352EF41F6688AD8408E42970B50B66
- generatedChecksum: 5591C3627E1EAF04874E2BAA428546AB
  logicalPath: config/mchv3_pic32_mk_mcm_pim/X2CCode/X2CScope
  name: X2CScope.h
  physicalPath: X2CCode/X2CScope/inc
  security: NON_SECURE
  type: HEADER
  userChecksum: 5591C3627E1EAF04874E2BAA428546AB
- generatedChecksum: CA44DEA5CA47431DCFE19A280CE9644A
  logicalPath: config/mchv3_pic32_mk_mcm_pim/X2CCode/X2CScope
  name: X2CScopeCommunication.h
  physicalPath: X2CCode/X2CScope/inc
  security: NON_SECURE
  type: HEADER
  userChecksum: CA44DEA5CA47431DCFE19A280CE9644A
- generatedChecksum: 1CC4A4F2A70990A31F79E1541BB62BE6
  logicalPath: config/mchv3_pic32_mk_mcm_pim/bsp
  name: bsp.h
  physicalPath: bsp
  security: NON_SECURE
  type: HEADER
  userChecksum: 1CC4A4F2A70990A31F79E1541BB62BE6
- generatedChecksum: F42E7EA287FBC59DFBF1CE3223138B43
  logicalPath: config/mchv3_pic32_mk_mcm_pim
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: F42E7EA287FBC59DFBF1CE3223138B43
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/mchv3_pic32_mk_mcm_pim
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/mchv3_pic32_mk_mcm_pim
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: F6ADBF8DEB5B9B32342DB12002355ED7
  logicalPath: config/mchv3_pic32_mk_mcm_pim/motor_control/pmsm_foc
  name: mc_current_calculation.h
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: HEADER
  userChecksum: F6ADBF8DEB5B9B32342DB12002355ED7
- generatedChecksum: 6A2C66F0E36E185E9B58DF5A14486F2E
  logicalPath: config/mchv3_pic32_mk_mcm_pim/motor_control/pmsm_foc
  name: mc_current_control.h
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: HEADER
  userChecksum: 6A2C66F0E36E185E9B58DF5A14486F2E
- generatedChecksum: CE14273787DADF09A07C74FEDC728200
  logicalPath: config/mchv3_pic32_mk_mcm_pim/motor_control/pmsm_foc
  name: mc_error_handler.h
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: HEADER
  userChecksum: CE14273787DADF09A07C74FEDC728200
- generatedChecksum: BC2C2AEEB30BA5F39DEDF5DA53D5F1D2
  logicalPath: config/mchv3_pic32_mk_mcm_pim/motor_control/pmsm_foc
  name: mc_flux_control.h
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: HEADER
  userChecksum: BC2C2AEEB30BA5F39DEDF5DA53D5F1D2
- generatedChecksum: 5DFAB3861682CC3CDC99AE7490E1A5D9
  logicalPath: config/mchv3_pic32_mk_mcm_pim/motor_control/pmsm_foc
  name: mc_flying_start.h
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: HEADER
  userChecksum: 5DFAB3861682CC3CDC99AE7490E1A5D9
- generatedChecksum: 1CC0E97CFEEA97A52AC7D629F3CA1F63
  logicalPath: config/mchv3_pic32_mk_mcm_pim/motor_control/pmsm_foc
  name: mc_function_coordinator.h
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: HEADER
  userChecksum: 1CC0E97CFEEA97A52AC7D629F3CA1F63
- generatedChecksum: 252A028B298701B1D1655A901AFF46E5
  logicalPath: config/mchv3_pic32_mk_mcm_pim/motor_control/pmsm_foc
  name: mc_generic_library.h
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: HEADER
  userChecksum: 252A028B298701B1D1655A901AFF46E5
- generatedChecksum: AC9FEA1F5B89D7074B40E917963F190A
  logicalPath: config/mchv3_pic32_mk_mcm_pim/motor_control/pmsm_foc
  name: mc_hardware_abstraction.h
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: HEADER
  userChecksum: AC9FEA1F5B89D7074B40E917963F190A
- generatedChecksum: 73A32F79998FFF7CE8A0579E79563F14
  logicalPath: config/mchv3_pic32_mk_mcm_pim/motor_control/pmsm_foc
  name: mc_interface_handling.h
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: HEADER
  userChecksum: 73A32F79998FFF7CE8A0579E79563F14
- generatedChecksum: 08A4407C90860AFB707AF7BB5DA98551
  logicalPath: config/mchv3_pic32_mk_mcm_pim/motor_control/pmsm_foc
  name: mc_motor_control.h
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: HEADER
  userChecksum: 08A4407C90860AFB707AF7BB5DA98551
- generatedChecksum: 6345B1A6E7FBC8E99D7341C940437600
  logicalPath: config/mchv3_pic32_mk_mcm_pim/motor_control/pmsm_foc
  name: mc_pmsm_foc.h
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: HEADER
  userChecksum: 6345B1A6E7FBC8E99D7341C940437600
- generatedChecksum: 0DD90CD0EFE1BF85221EAD989CC5AEAF
  logicalPath: config/mchv3_pic32_mk_mcm_pim/motor_control/pmsm_foc
  name: mc_position_control.h
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: HEADER
  userChecksum: 0DD90CD0EFE1BF85221EAD989CC5AEAF
- generatedChecksum: 7B450C95D2E7C2DCE4415246F27BD1BE
  logicalPath: config/mchv3_pic32_mk_mcm_pim/motor_control/pmsm_foc
  name: mc_pwm.h
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: HEADER
  userChecksum: 7B450C95D2E7C2DCE4415246F27BD1BE
- generatedChecksum: 01B3DA2CA271B7E68657CDB478CEED91
  logicalPath: config/mchv3_pic32_mk_mcm_pim/motor_control/pmsm_foc
  name: mc_ramp_profiler.h
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: HEADER
  userChecksum: 01B3DA2CA271B7E68657CDB478CEED91
- generatedChecksum: DC188F39DE06A22F197722B16C01D917
  logicalPath: config/mchv3_pic32_mk_mcm_pim/motor_control/pmsm_foc
  name: mc_rotor_position.h
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: HEADER
  userChecksum: DC188F39DE06A22F197722B16C01D917
- generatedChecksum: 5BCB8D8F319DF0B7952A8241E28EA8A8
  logicalPath: config/mchv3_pic32_mk_mcm_pim/motor_control/pmsm_foc
  name: mc_speed_control.h
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: HEADER
  userChecksum: 5BCB8D8F319DF0B7952A8241E28EA8A8
- generatedChecksum: D47DE66CAB23E081E97E541C7A94E941
  logicalPath: config/mchv3_pic32_mk_mcm_pim/motor_control/pmsm_foc
  name: mc_start_up.h
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: HEADER
  userChecksum: D47DE66CAB23E081E97E541C7A94E941
- generatedChecksum: CA817C5A416EF7EAAF1725C87671792E
  logicalPath: config/mchv3_pic32_mk_mcm_pim/motor_control/pmsm_foc
  name: mc_userparams.h
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: HEADER
  userChecksum: CA817C5A416EF7EAAF1725C87671792E
- generatedChecksum: F1C5034F7E74D1F41FCC75861A321FCF
  logicalPath: config/mchv3_pic32_mk_mcm_pim/motor_control/pmsm_foc
  name: mc_voltage_measurement.h
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: HEADER
  userChecksum: F1C5034F7E74D1F41FCC75861A321FCF
- generatedChecksum: 5EE492EE9E54347ED49C78048AF79CEC
  logicalPath: config/mchv3_pic32_mk_mcm_pim/peripheral/adchs
  name: plib_adchs.h
  physicalPath: peripheral/adchs
  security: NON_SECURE
  type: HEADER
  userChecksum: 5EE492EE9E54347ED49C78048AF79CEC
- generatedChecksum: 9BC740B9E11F5CABC4A22BD0F7689C26
  logicalPath: config/mchv3_pic32_mk_mcm_pim/peripheral/adchs
  name: plib_adchs_common.h
  physicalPath: peripheral/adchs
  security: NON_SECURE
  type: HEADER
  userChecksum: 9BC740B9E11F5CABC4A22BD0F7689C26
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/mchv3_pic32_mk_mcm_pim/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 4D592E1C42727324FE2F5EB681F6C5AA
  logicalPath: config/mchv3_pic32_mk_mcm_pim/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 4D592E1C42727324FE2F5EB681F6C5AA
- generatedChecksum: 35B6A0B948FCAAF3AB1E1E7E42FE15DD
  logicalPath: config/mchv3_pic32_mk_mcm_pim/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 0B5BBA9E5FE777E0FB97EA69952E23AF
- generatedChecksum: 12CBE2439F4C4DECD2B376033BBADA45
  logicalPath: config/mchv3_pic32_mk_mcm_pim/peripheral/mcpwm
  name: plib_mcpwm.h
  physicalPath: peripheral/mcpwm
  security: NON_SECURE
  type: HEADER
  userChecksum: 12CBE2439F4C4DECD2B376033BBADA45
- generatedChecksum: 8C0682DB8DD38F7C09771C63347D06FF
  logicalPath: config/mchv3_pic32_mk_mcm_pim/peripheral/mcpwm
  name: plib_mcpwm_common.h
  physicalPath: peripheral/mcpwm
  security: NON_SECURE
  type: HEADER
  userChecksum: 8C0682DB8DD38F7C09771C63347D06FF
- generatedChecksum: 687F99E456839E29578ACB606A2A0083
  logicalPath: config/mchv3_pic32_mk_mcm_pim/peripheral/uart
  name: plib_uart2.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 687F99E456839E29578ACB606A2A0083
- generatedChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
  logicalPath: config/mchv3_pic32_mk_mcm_pim/peripheral/uart
  name: plib_uart_common.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
- generatedChecksum: 7DC91D6D376C98802C9C2990432DE9B7
  logicalPath: config/mchv3_pic32_mk_mcm_pim
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 7DC91D6D376C98802C9C2990432DE9B7
- generatedChecksum: 076A5CDEAE185EDCB946BAC9F1AD03E5
  logicalPath: config/mchv3_pic32_mk_mcm_pim
  name: p32MK1024MCM100.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 076A5CDEAE185EDCB946BAC9F1AD03E5
format_version: v1.0
libraries:
- name: libPIC32MK_X2CScope.a
  path: /X2CCode/X2CScope/lib/
  security: NON_SECURE
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src/config/mchv3_pic32_mk_mcm_pim/X2CCode
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/mchv3_pic32_mk_mcm_pim;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/mchv3_pic32_mk_mcm_pim;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
