format_version: v1.0
type: UniqueComponent
attributes: {id: BSP_PIC32MK_MCF_PIM_MC_Board, bsp: 'true'}
children:
- type: ElementPosition
  attributes: {x: '82', y: '495', id: BSP_PIC32MK_MCF_PIM_MC_Board}
