format_version: v1.0
type: UniqueComponent
attributes: {id: pmsm_foc}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: MCPMSMFOC_ADC_MODULE_01}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: adchs}
  - type: Combo
    attributes: {id: MCPMSMFOC_BUS_VOLTAGE_VDC_UNIT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: ADC7}
  - type: Combo
    attributes: {id: MCPMSMFOC_BUS_VOLTAGE_VDC_UNIT_BUS_VOLTAGE_VDC_ADC7}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: Channel 10}
  - type: String
    attributes: {id: MCPMSMFOC_BUS_VOLTAGE_VDC_UNIT_BUS_VOLTAGE_VDC_FINAL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '10'}
  - type: Integer
    attributes: {id: MCPMSMFOC_BUTTONS_AVAILABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '2'}
  - type: String
    attributes: {id: MCPMSMFOC_BUTTON_0_NAME}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: BUTTON_01}
  - type: Combo
    attributes: {id: MCPMSMFOC_BUTTON_0_NUMBER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: RG1}
  - type: String
    attributes: {id: MCPMSMFOC_BUTTON_1_NAME}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: BUTTON_02}
  - type: Combo
    attributes: {id: MCPMSMFOC_BUTTON_1_NUMBER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: RC7}
  - type: Menu
    attributes: {id: MCPMSMFOC_ED_FILTER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: String
    attributes: {id: MCPMSMFOC_ENCODERPLIB}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: qei2}
  - type: Combo
    attributes: {id: MCPMSMFOC_ENCODER_PERIPHERAL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: QEI2}
  - type: String
    attributes: {id: MCPMSMFOC_ENCODER_PERIPHERAL_QEA_FINAL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '2'}
  - type: String
    attributes: {id: MCPMSMFOC_ENCODER_PERIPHERAL_QEB_FINAL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '2'}
  - type: Menu
    attributes: {id: MCPMSMFOC_EQ_FILTER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Integer
    attributes: {id: MCPMSMFOC_LEDS_AVAILABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '2'}
  - type: String
    attributes: {id: MCPMSMFOC_LED_0_NAME}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: LED_01}
  - type: Combo
    attributes: {id: MCPMSMFOC_LED_0_NUMBER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: RF5}
  - type: String
    attributes: {id: MCPMSMFOC_LED_1_NAME}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: LED_02}
  - type: Combo
    attributes: {id: MCPMSMFOC_LED_1_NUMBER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: RG15}
  - type: KeyValueSet
    attributes: {id: MCPMSMFOC_MOTOR_CONNECTION}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '0'}
  - type: Combo
    attributes: {id: MCPMSMFOC_PHASE_CURRENT_IA_UNIT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: ADC0}
  - type: Combo
    attributes: {id: MCPMSMFOC_PHASE_CURRENT_IA_UNIT_PHASE_CURRENT_IA_ADC0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: Channel 24}
  - type: String
    attributes: {id: MCPMSMFOC_PHASE_CURRENT_IA_UNIT_PHASE_CURRENT_IA_FINAL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '24'}
  - type: Combo
    attributes: {id: MCPMSMFOC_PHASE_CURRENT_IB_UNIT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: ADC4}
  - type: Combo
    attributes: {id: MCPMSMFOC_PHASE_CURRENT_IB_UNIT_PHASE_CURRENT_IB_ADC4}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: Channel 9}
  - type: String
    attributes: {id: MCPMSMFOC_PHASE_CURRENT_IB_UNIT_PHASE_CURRENT_IB_FINAL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '9'}
  - type: KeyValueSet
    attributes: {id: MCPMSMFOC_POSITION_CALC_ALGORITHM}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: File
    attributes: {id: MCPMSMFOC_POS_PLL_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: MCPMSMFOC_POS_PLL_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: MCPMSMFOC_POS_ROLO_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: MCPMSMFOC_POS_ROLO_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: MCPMSMFOC_POS_SMO_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: MCPMSMFOC_POS_SMO_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: Combo
    attributes: {id: MCPMSMFOC_POTENTIOMETER_VPOT_UNIT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: ADC7}
  - type: Combo
    attributes: {id: MCPMSMFOC_POTENTIOMETER_VPOT_UNIT_POTENTIOMETER_VPOT_ADC7}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: Channel 15}
  - type: String
    attributes: {id: MCPMSMFOC_POTENTIOMETER_VPOT_UNIT_POTENTIOMETER_VPOT_FINAL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '15'}
  - type: String
    attributes: {id: MCPMSMFOC_PWMPLIB}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: mcpwm}
  - type: Combo
    attributes: {id: MCPMSMFOC_PWM_INSTANCE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: MCPWM}
  - type: String
    attributes: {id: MCPMSMFOC_PWM_INSTANCE_PWM_A_FINAL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '1'}
  - type: String
    attributes: {id: MCPMSMFOC_PWM_INSTANCE_PWM_B_FINAL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '2'}
  - type: String
    attributes: {id: MCPMSMFOC_PWM_INSTANCE_PWM_C_FINAL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '3'}
  - type: Menu
    attributes: {id: MCPMSMFOC_SPEED_FILTER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: String
    attributes: {id: MCPMSMFOC_X2CScope}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: X2CScope}
- type: Attachments
  children:
  - type: MultiCapability
    attributes: {id: pmsmfoc_ADC}
    children:
    - type: TargetAttachments
      children:
      - type: TargetAttachment
        attributes: {targetComponentID: adchs, targetAttachmentID: ADCHS_ADC}
  - type: DirectDependency
    attributes: {id: pmsmfoc_PWM}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: mcpwm}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: MCPWM_PWM}
  - type: DirectDependency
    attributes: {id: pmsmfoc_QDEC}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: qei2}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: QEI2_QDEC}
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: DirectDependency
    attributes: {id: pmsmfoc_X2CSCOPE}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: X2CScope}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: x2cScope_Scope}
- type: ElementPosition
  attributes: {x: '296', y: '201', id: pmsm_foc}
