files:
- generatedChecksum: DBEB484D45D924F226145E41226877FB
  logicalPath: config/mclv2_pic32_mk_mcf_pim/X2CCode/X2CScope
  name: X2CScope.c
  physicalPath: X2CCode/X2CScope/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: DBEB484D45D924F226145E41226877FB
- generatedChecksum: 8B8EDEA47D6019608B1C479D3DA3B114
  logicalPath: config/mclv2_pic32_mk_mcf_pim/X2CCode/X2CScope
  name: X2CScopeCommunication.c
  physicalPath: X2CCode/X2CScope/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 8B8EDEA47D6019608B1C479D3DA3B114
- generatedChecksum: 2F6CC050E57B9E5BA8A6C6C9A2D8F09A
  logicalPath: config/mclv2_pic32_mk_mcf_pim/bsp
  name: bsp.c
  physicalPath: bsp
  security: NON_SECURE
  type: SOURCE
  userChecksum: 2F6CC050E57B9E5BA8A6C6C9A2D8F09A
- generatedChecksum: 99DB74296DF9943C474F4F03A700C790
  logicalPath: config/mclv2_pic32_mk_mcf_pim
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 99DB74296DF9943C474F4F03A700C790
- generatedChecksum: 7F1D40BF58B56A5511E130674C65B032
  logicalPath: config/mclv2_pic32_mk_mcf_pim
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7F1D40BF58B56A5511E130674C65B032
- generatedChecksum: 8484E40ECBDA44571EAC5076FB530F41
  logicalPath: config/mclv2_pic32_mk_mcf_pim
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 8484E40ECBDA44571EAC5076FB530F41
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 9ED9B589DCF5759C4AE8D01844964040
  logicalPath: config/mclv2_pic32_mk_mcf_pim/motor_control/pmsm_foc
  name: mc_current_calculation.c
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: SOURCE
  userChecksum: 9ED9B589DCF5759C4AE8D01844964040
- generatedChecksum: C5232945CF588E50C7F21608CD160269
  logicalPath: config/mclv2_pic32_mk_mcf_pim/motor_control/pmsm_foc
  name: mc_current_control.c
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: SOURCE
  userChecksum: C5232945CF588E50C7F21608CD160269
- generatedChecksum: 5BF6505AB140C800F875CE33A240DC60
  logicalPath: config/mclv2_pic32_mk_mcf_pim/motor_control/pmsm_foc
  name: mc_error_handler.c
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: SOURCE
  userChecksum: 5BF6505AB140C800F875CE33A240DC60
- generatedChecksum: 50C81F481EB4F4BDD498B737A271BBD4
  logicalPath: config/mclv2_pic32_mk_mcf_pim/motor_control/pmsm_foc
  name: mc_flux_control.c
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: SOURCE
  userChecksum: 50C81F481EB4F4BDD498B737A271BBD4
- generatedChecksum: 2CCE8E5F8013E2EFDA2F6FC79F34FEFA
  logicalPath: config/mclv2_pic32_mk_mcf_pim/motor_control/pmsm_foc
  name: mc_flying_start.c
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: SOURCE
  userChecksum: 2CCE8E5F8013E2EFDA2F6FC79F34FEFA
- generatedChecksum: F2162427696EE8CB497E2EF89C24D2B2
  logicalPath: config/mclv2_pic32_mk_mcf_pim/motor_control/pmsm_foc
  name: mc_function_coordinator.c
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: SOURCE
  userChecksum: 33A5BAF3E6005EE8945FF36B32851036
- generatedChecksum: FE85230893E6F14C25F5CC48CC8B17B9
  logicalPath: config/mclv2_pic32_mk_mcf_pim/motor_control/pmsm_foc
  name: mc_generic_library.c
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: SOURCE
  userChecksum: FE85230893E6F14C25F5CC48CC8B17B9
- generatedChecksum: 509D718E6C84633C0E7D42CE0BD086CE
  logicalPath: config/mclv2_pic32_mk_mcf_pim/motor_control/pmsm_foc
  name: mc_hardware_abstraction.c
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: SOURCE
  userChecksum: 509D718E6C84633C0E7D42CE0BD086CE
- generatedChecksum: BEADE8301C4C35BFFC3A1F0BF71CE6D3
  logicalPath: config/mclv2_pic32_mk_mcf_pim/motor_control/pmsm_foc
  name: mc_interface_handling.c
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: SOURCE
  userChecksum: BEADE8301C4C35BFFC3A1F0BF71CE6D3
- generatedChecksum: 3B154B021AFA4C157A9920942191B771
  logicalPath: config/mclv2_pic32_mk_mcf_pim/motor_control/pmsm_foc
  name: mc_motor_control.c
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: SOURCE
  userChecksum: 3B154B021AFA4C157A9920942191B771
- generatedChecksum: 713B191884A77E5402B7DD70FA0677BB
  logicalPath: config/mclv2_pic32_mk_mcf_pim/motor_control/pmsm_foc
  name: mc_pmsm_foc.c
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: SOURCE
  userChecksum: 713B191884A77E5402B7DD70FA0677BB
- generatedChecksum: 2337846FBCA5C415C4286B488D58BF83
  logicalPath: config/mclv2_pic32_mk_mcf_pim/motor_control/pmsm_foc
  name: mc_position_control.c
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: SOURCE
  userChecksum: 2337846FBCA5C415C4286B488D58BF83
- generatedChecksum: A913561E1120E5A256A1858BAFC9B0BE
  logicalPath: config/mclv2_pic32_mk_mcf_pim/motor_control/pmsm_foc
  name: mc_pwm.c
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: SOURCE
  userChecksum: A913561E1120E5A256A1858BAFC9B0BE
- generatedChecksum: ABAC8ACF6A85B28A42FA852F02319B96
  logicalPath: config/mclv2_pic32_mk_mcf_pim/motor_control/pmsm_foc
  name: mc_ramp_profiler.c
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: SOURCE
  userChecksum: ABAC8ACF6A85B28A42FA852F02319B96
- generatedChecksum: 8D82A37813FE8D44542AE4DD8BDA9D9F
  logicalPath: config/mclv2_pic32_mk_mcf_pim/motor_control/pmsm_foc
  name: mc_rotor_position.c
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: SOURCE
  userChecksum: 8D82A37813FE8D44542AE4DD8BDA9D9F
- generatedChecksum: 6691D9C1973389A06F4F743B0125633C
  logicalPath: config/mclv2_pic32_mk_mcf_pim/motor_control/pmsm_foc
  name: mc_speed_control.c
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: SOURCE
  userChecksum: 6691D9C1973389A06F4F743B0125633C
- generatedChecksum: E68EF87040FFED2EB2CB8B7C77139EFD
  logicalPath: config/mclv2_pic32_mk_mcf_pim/motor_control/pmsm_foc
  name: mc_start_up.c
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: SOURCE
  userChecksum: E68EF87040FFED2EB2CB8B7C77139EFD
- generatedChecksum: 4E37588BB0DD75FC73026EB88E428BB0
  logicalPath: config/mclv2_pic32_mk_mcf_pim/motor_control/pmsm_foc
  name: mc_voltage_measurement.c
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4E37588BB0DD75FC73026EB88E428BB0
- generatedChecksum: C0393C9EBF4A49E69BA69B3279FC07C1
  logicalPath: config/mclv2_pic32_mk_mcf_pim/peripheral/adchs
  name: plib_adchs.c
  physicalPath: peripheral/adchs
  security: NON_SECURE
  type: SOURCE
  userChecksum: C0393C9EBF4A49E69BA69B3279FC07C1
- generatedChecksum: 6494DE3CB5029E84109BFD19FEE1BB53
  logicalPath: config/mclv2_pic32_mk_mcf_pim/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 6494DE3CB5029E84109BFD19FEE1BB53
- generatedChecksum: DD8FC2825355F316F9799F5CC082FF05
  logicalPath: config/mclv2_pic32_mk_mcf_pim/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: DD8FC2825355F316F9799F5CC082FF05
- generatedChecksum: 156ECEC03775F7B127A1C57D376F1DE7
  logicalPath: config/mclv2_pic32_mk_mcf_pim/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 156ECEC03775F7B127A1C57D376F1DE7
- generatedChecksum: 14EC08B2B2233854BC4CDD8F98BA1892
  logicalPath: config/mclv2_pic32_mk_mcf_pim/peripheral/mcpwm
  name: plib_mcpwm.c
  physicalPath: peripheral/mcpwm
  security: NON_SECURE
  type: SOURCE
  userChecksum: 14EC08B2B2233854BC4CDD8F98BA1892
- generatedChecksum: 7D9E7E1EF7B91F5B453BE4242B04A2B3
  logicalPath: config/mclv2_pic32_mk_mcf_pim/peripheral/qei
  name: plib_qei2.c
  physicalPath: peripheral/qei
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7D9E7E1EF7B91F5B453BE4242B04A2B3
- generatedChecksum: 0E74E8218E54427BDBAE8B4238D55E4C
  logicalPath: config/mclv2_pic32_mk_mcf_pim/peripheral/uart
  name: plib_uart2.c
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 0E74E8218E54427BDBAE8B4238D55E4C
- generatedChecksum: 7806B30ECAE0D18D08CD583D8775530D
  logicalPath: config/mclv2_pic32_mk_mcf_pim/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7806B30ECAE0D18D08CD583D8775530D
- generatedChecksum: 5591C3627E1EAF04874E2BAA428546AB
  logicalPath: config/mclv2_pic32_mk_mcf_pim/X2CCode/X2CScope
  name: X2CScope.h
  physicalPath: X2CCode/X2CScope/inc
  security: NON_SECURE
  type: HEADER
  userChecksum: 5591C3627E1EAF04874E2BAA428546AB
- generatedChecksum: CA44DEA5CA47431DCFE19A280CE9644A
  logicalPath: config/mclv2_pic32_mk_mcf_pim/X2CCode/X2CScope
  name: X2CScopeCommunication.h
  physicalPath: X2CCode/X2CScope/inc
  security: NON_SECURE
  type: HEADER
  userChecksum: CA44DEA5CA47431DCFE19A280CE9644A
- generatedChecksum: 1CC4A4F2A70990A31F79E1541BB62BE6
  logicalPath: config/mclv2_pic32_mk_mcf_pim/bsp
  name: bsp.h
  physicalPath: bsp
  security: NON_SECURE
  type: HEADER
  userChecksum: 1CC4A4F2A70990A31F79E1541BB62BE6
- generatedChecksum: CA05E7AEF3BFC55974E8398E1D87AEBC
  logicalPath: config/mclv2_pic32_mk_mcf_pim
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: CA05E7AEF3BFC55974E8398E1D87AEBC
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/mclv2_pic32_mk_mcf_pim
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/mclv2_pic32_mk_mcf_pim
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: F6ADBF8DEB5B9B32342DB12002355ED7
  logicalPath: config/mclv2_pic32_mk_mcf_pim/motor_control/pmsm_foc
  name: mc_current_calculation.h
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: HEADER
  userChecksum: F6ADBF8DEB5B9B32342DB12002355ED7
- generatedChecksum: 6A2C66F0E36E185E9B58DF5A14486F2E
  logicalPath: config/mclv2_pic32_mk_mcf_pim/motor_control/pmsm_foc
  name: mc_current_control.h
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: HEADER
  userChecksum: 6A2C66F0E36E185E9B58DF5A14486F2E
- generatedChecksum: CE14273787DADF09A07C74FEDC728200
  logicalPath: config/mclv2_pic32_mk_mcf_pim/motor_control/pmsm_foc
  name: mc_error_handler.h
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: HEADER
  userChecksum: CE14273787DADF09A07C74FEDC728200
- generatedChecksum: 83AA93F86030284AED857A21557A9879
  logicalPath: config/mclv2_pic32_mk_mcf_pim/motor_control/pmsm_foc
  name: mc_flux_control.h
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: HEADER
  userChecksum: 83AA93F86030284AED857A21557A9879
- generatedChecksum: 5DFAB3861682CC3CDC99AE7490E1A5D9
  logicalPath: config/mclv2_pic32_mk_mcf_pim/motor_control/pmsm_foc
  name: mc_flying_start.h
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: HEADER
  userChecksum: 5DFAB3861682CC3CDC99AE7490E1A5D9
- generatedChecksum: 1CC0E97CFEEA97A52AC7D629F3CA1F63
  logicalPath: config/mclv2_pic32_mk_mcf_pim/motor_control/pmsm_foc
  name: mc_function_coordinator.h
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: HEADER
  userChecksum: 1CC0E97CFEEA97A52AC7D629F3CA1F63
- generatedChecksum: FB27DA752473B11D4D7774ACB210CF5D
  logicalPath: config/mclv2_pic32_mk_mcf_pim/motor_control/pmsm_foc
  name: mc_generic_library.h
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: HEADER
  userChecksum: FB27DA752473B11D4D7774ACB210CF5D
- generatedChecksum: FDCDD6E8DC7FFF4612C7EC91A74A71D2
  logicalPath: config/mclv2_pic32_mk_mcf_pim/motor_control/pmsm_foc
  name: mc_hardware_abstraction.h
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: HEADER
  userChecksum: FDCDD6E8DC7FFF4612C7EC91A74A71D2
- generatedChecksum: 9A362A8F938E9B5736873D094F01E41A
  logicalPath: config/mclv2_pic32_mk_mcf_pim/motor_control/pmsm_foc
  name: mc_interface_handling.h
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: HEADER
  userChecksum: 9A362A8F938E9B5736873D094F01E41A
- generatedChecksum: 08A4407C90860AFB707AF7BB5DA98551
  logicalPath: config/mclv2_pic32_mk_mcf_pim/motor_control/pmsm_foc
  name: mc_motor_control.h
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: HEADER
  userChecksum: 08A4407C90860AFB707AF7BB5DA98551
- generatedChecksum: 6345B1A6E7FBC8E99D7341C940437600
  logicalPath: config/mclv2_pic32_mk_mcf_pim/motor_control/pmsm_foc
  name: mc_pmsm_foc.h
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: HEADER
  userChecksum: 6345B1A6E7FBC8E99D7341C940437600
- generatedChecksum: 0DD90CD0EFE1BF85221EAD989CC5AEAF
  logicalPath: config/mclv2_pic32_mk_mcf_pim/motor_control/pmsm_foc
  name: mc_position_control.h
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: HEADER
  userChecksum: 0DD90CD0EFE1BF85221EAD989CC5AEAF
- generatedChecksum: 7B450C95D2E7C2DCE4415246F27BD1BE
  logicalPath: config/mclv2_pic32_mk_mcf_pim/motor_control/pmsm_foc
  name: mc_pwm.h
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: HEADER
  userChecksum: 7B450C95D2E7C2DCE4415246F27BD1BE
- generatedChecksum: 01B3DA2CA271B7E68657CDB478CEED91
  logicalPath: config/mclv2_pic32_mk_mcf_pim/motor_control/pmsm_foc
  name: mc_ramp_profiler.h
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: HEADER
  userChecksum: 01B3DA2CA271B7E68657CDB478CEED91
- generatedChecksum: 3248A31C277771DD292507F8CE513B56
  logicalPath: config/mclv2_pic32_mk_mcf_pim/motor_control/pmsm_foc
  name: mc_rotor_position.h
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: HEADER
  userChecksum: 3248A31C277771DD292507F8CE513B56
- generatedChecksum: E6A119E9558C6A45DC727E6CEA0A0360
  logicalPath: config/mclv2_pic32_mk_mcf_pim/motor_control/pmsm_foc
  name: mc_speed_control.h
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: HEADER
  userChecksum: E6A119E9558C6A45DC727E6CEA0A0360
- generatedChecksum: D47DE66CAB23E081E97E541C7A94E941
  logicalPath: config/mclv2_pic32_mk_mcf_pim/motor_control/pmsm_foc
  name: mc_start_up.h
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: HEADER
  userChecksum: D47DE66CAB23E081E97E541C7A94E941
- generatedChecksum: 662BE1C8AAA977E77D3E9B63F470E567
  logicalPath: config/mclv2_pic32_mk_mcf_pim/motor_control/pmsm_foc
  name: mc_userparams.h
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: HEADER
  userChecksum: 662BE1C8AAA977E77D3E9B63F470E567
- generatedChecksum: B586D1C045EC4A1A677256CFA91159BE
  logicalPath: config/mclv2_pic32_mk_mcf_pim/motor_control/pmsm_foc
  name: mc_voltage_measurement.h
  physicalPath: motor_control/pmsm_foc
  security: NON_SECURE
  type: HEADER
  userChecksum: B586D1C045EC4A1A677256CFA91159BE
- generatedChecksum: 74058744638925EEB20F58B4328F1B68
  logicalPath: config/mclv2_pic32_mk_mcf_pim/peripheral/adchs
  name: plib_adchs.h
  physicalPath: peripheral/adchs
  security: NON_SECURE
  type: HEADER
  userChecksum: 74058744638925EEB20F58B4328F1B68
- generatedChecksum: C33A7F48915DF50A82501D3A25FB312C
  logicalPath: config/mclv2_pic32_mk_mcf_pim/peripheral/adchs
  name: plib_adchs_common.h
  physicalPath: peripheral/adchs
  security: NON_SECURE
  type: HEADER
  userChecksum: C33A7F48915DF50A82501D3A25FB312C
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/mclv2_pic32_mk_mcf_pim/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: B78FF86E447151F5314DE7C6C7324628
  logicalPath: config/mclv2_pic32_mk_mcf_pim/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: B78FF86E447151F5314DE7C6C7324628
- generatedChecksum: 38F9DBBEBE0E990535B138CB06577FA2
  logicalPath: config/mclv2_pic32_mk_mcf_pim/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 38F9DBBEBE0E990535B138CB06577FA2
- generatedChecksum: 12CBE2439F4C4DECD2B376033BBADA45
  logicalPath: config/mclv2_pic32_mk_mcf_pim/peripheral/mcpwm
  name: plib_mcpwm.h
  physicalPath: peripheral/mcpwm
  security: NON_SECURE
  type: HEADER
  userChecksum: 12CBE2439F4C4DECD2B376033BBADA45
- generatedChecksum: 8C0682DB8DD38F7C09771C63347D06FF
  logicalPath: config/mclv2_pic32_mk_mcf_pim/peripheral/mcpwm
  name: plib_mcpwm_common.h
  physicalPath: peripheral/mcpwm
  security: NON_SECURE
  type: HEADER
  userChecksum: 8C0682DB8DD38F7C09771C63347D06FF
- generatedChecksum: 4B8232F9FE5AC341D05549F00197BAAE
  logicalPath: config/mclv2_pic32_mk_mcf_pim/peripheral/qei
  name: plib_qei2.h
  physicalPath: peripheral/qei
  security: NON_SECURE
  type: HEADER
  userChecksum: 4B8232F9FE5AC341D05549F00197BAAE
- generatedChecksum: D6A76BFCD1B06AC07959D1D4CB4D2B3E
  logicalPath: config/mclv2_pic32_mk_mcf_pim/peripheral/qei
  name: plib_qei_common.h
  physicalPath: peripheral/qei
  security: NON_SECURE
  type: HEADER
  userChecksum: D6A76BFCD1B06AC07959D1D4CB4D2B3E
- generatedChecksum: 687F99E456839E29578ACB606A2A0083
  logicalPath: config/mclv2_pic32_mk_mcf_pim/peripheral/uart
  name: plib_uart2.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 687F99E456839E29578ACB606A2A0083
- generatedChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
  logicalPath: config/mclv2_pic32_mk_mcf_pim/peripheral/uart
  name: plib_uart_common.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
- generatedChecksum: 7DC91D6D376C98802C9C2990432DE9B7
  logicalPath: config/mclv2_pic32_mk_mcf_pim
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 7DC91D6D376C98802C9C2990432DE9B7
- generatedChecksum: FC05EB67A0DDF86BB9693CB7FE50E954
  logicalPath: config/mclv2_pic32_mk_mcf_pim
  name: p32MK1024MCF100.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: FC05EB67A0DDF86BB9693CB7FE50E954
format_version: v1.0
libraries:
- name: libPIC32MK_X2CScope.a
  path: /X2CCode/X2CScope/lib/
  security: NON_SECURE
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src/config/mclv2_pic32_mk_mcf_pim/X2CCode
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/mclv2_pic32_mk_mcf_pim;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/mclv2_pic32_mk_mcf_pim;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
