format_version: v1.0
type: UniqueComponent
attributes: {id: adchs}
children:
- type: Symbols
  children:
  - type: KeyValueSet
    attributes: {id: ADC0TIME__SELRES}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '3'}
  - type: KeyValueSet
    attributes: {id: ADC4TIME__SELRES}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '3'}
  - type: KeyValueSet
    attributes: {id: ADCCON1__SELRES}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '3'}
  - type: Boolean
    attributes: {id: ADCGIRQEN1__AGIEN0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: 'true'}
  - type: Boolean
    attributes: {id: ADCHS_0_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: 'true'}
  - type: Boolean
    attributes: {id: ADCHS_4_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: 'true'}
  - type: Boolean
    attributes: {id: ADCHS_7_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: 'true'}
  - type: Hex
    attributes: {id: ADCHS_ADCCON1}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '6291456'}
  - type: Hex
    attributes: {id: ADCHS_ADCCON2}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '131073'}
  - type: Hex
    attributes: {id: ADCHS_ADCCSS1}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '0'}
  - type: Hex
    attributes: {id: ADCHS_ADCCSS2}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '0'}
  - type: Hex
    attributes: {id: ADCHS_ADCGIRQEN1}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '1'}
  - type: Hex
    attributes: {id: ADCHS_ADCIMCON1}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '0'}
  - type: Hex
    attributes: {id: ADCHS_ADCTIME0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '50397185'}
  - type: Hex
    attributes: {id: ADCHS_ADCTIME1}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '50397185'}
  - type: Hex
    attributes: {id: ADCHS_ADCTIME2}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '50397185'}
  - type: Hex
    attributes: {id: ADCHS_ADCTIME3}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '50397185'}
  - type: Hex
    attributes: {id: ADCHS_ADCTIME4}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '50397185'}
  - type: Hex
    attributes: {id: ADCHS_ADCTIME5}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '50397185'}
  - type: Hex
    attributes: {id: ADCHS_ADCTRG1}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '10'}
  - type: Hex
    attributes: {id: ADCHS_ADCTRG2}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '10'}
  - type: Hex
    attributes: {id: ADCHS_ADCTRG3}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '655360'}
  - type: Hex
    attributes: {id: ADCHS_ADCTRG4}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '167772160'}
  - type: Hex
    attributes: {id: ADCHS_ADCTRG5}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '0'}
  - type: Hex
    attributes: {id: ADCHS_ADCTRG6}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '0'}
  - type: Hex
    attributes: {id: ADCHS_ADCTRG7}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '0'}
  - type: Hex
    attributes: {id: ADCHS_ADCTRGMODE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '33751040'}
  - type: Float
    attributes: {id: ADCHS_CONV_RATE0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '937.50006'}
  - type: Float
    attributes: {id: ADCHS_CONV_RATE1}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '937.50006'}
  - type: Float
    attributes: {id: ADCHS_CONV_RATE2}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '937.50006'}
  - type: Float
    attributes: {id: ADCHS_CONV_RATE3}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '937.50006'}
  - type: Float
    attributes: {id: ADCHS_CONV_RATE4}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '937.50006'}
  - type: Float
    attributes: {id: ADCHS_CONV_RATE5}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '937.50006'}
  - type: Float
    attributes: {id: ADCHS_CONV_RATE7}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '882.35297'}
  - type: Hex
    attributes: {id: ADCHS_IEC0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '1024'}
  - type: Boolean
    attributes: {id: ADCHS_INTERRUPT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: 'true'}
  - type: Float
    attributes: {id: ADCHS_TADC0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '66.666664'}
  - type: Float
    attributes: {id: ADCHS_TADC1}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '66.666664'}
  - type: Float
    attributes: {id: ADCHS_TADC2}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '66.666664'}
  - type: Float
    attributes: {id: ADCHS_TADC3}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '66.666664'}
  - type: Float
    attributes: {id: ADCHS_TADC4}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '66.666664'}
  - type: Float
    attributes: {id: ADCHS_TADC5}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '66.666664'}
  - type: Float
    attributes: {id: ADCHS_TADC7}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '66.666664'}
  - type: Float
    attributes: {id: ADCHS_TCLK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '16.666666'}
  - type: Float
    attributes: {id: ADCHS_TQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '33.333332'}
  - type: KeyValueSet
    attributes: {id: ADCTRG1__TRGSRC0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '10'}
  - type: KeyValueSet
    attributes: {id: ADCTRG2__TRGSRC4}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '10'}
  - type: KeyValueSet
    attributes: {id: ADCTRG3__TRGSRC10}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '10'}
  - type: KeyValueSet
    attributes: {id: ADCTRG4__TRGSRC15}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '10'}
  - type: KeyValueSet
    attributes: {id: ADCTRGMODE__SH0ALT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '3'}
  - type: KeyValueSet
    attributes: {id: ADCTRGMODE__SH4ALT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '2'}
  - type: String
    attributes: {id: ADC_CALLBACK_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: ADCHS_CallbackRegister}
  - type: String
    attributes: {id: ADC_CH_PHASE_U}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: ADCHS_CH0}
  - type: String
    attributes: {id: ADC_CH_PHASE_V}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: ADCHS_CH4}
  - type: String
    attributes: {id: ADC_CH_POT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: ADCHS_CH15}
  - type: String
    attributes: {id: ADC_CH_VDC_BUS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: ADCHS_CH10}
  - type: String
    attributes: {id: ADC_GET_RESULT_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: ADCHS_ChannelResultGet}
  - type: String
    attributes: {id: ADC_IS_RESULT_READY_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: ADCHS_ChannelResultIsReady}
  - type: String
    attributes: {id: ADC_START_CONV_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: ADCHS_ChannelConversionStart}
  - type: Boolean
    attributes: {id: AN0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: 'true'}
  - type: Boolean
    attributes: {id: AN10}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: 'true'}
  - type: Boolean
    attributes: {id: AN15}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: 'true'}
  - type: Boolean
    attributes: {id: AN4}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: 'true'}
  - type: String
    attributes: {id: INTERRUPT_ADC_RESULT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: INT_SOURCE_ADC_DATA0}
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: ADCHS_ADC}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: pmsm_foc}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: pmsmfoc_ADC}
- type: ElementPosition
  attributes: {x: '237', y: '51', id: adchs}
