configName: mchv3_pic32_mk_mcf_pim
folderName: mchv3_pic32_mk_mcf_pim
format_version: v1.0
frameworkPath: ..\..\..
processor: PIC32MK1024MCF100
projectName: mchv3_pic32_mk_mcf_pim
settings:
  PackageFilter: bsp;csp;Devices;dev_packs;harmony-services;mc_apps_pic32cm_mc;mc_apps_pic32mk;mc_apps_pic32mk
    - Copy;mc_apps_sam_c2x;mc_apps_sam_d5x_e5x;mc_apps_sam_e7x_s7x_v7x;motor_control;x2c
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32MK-MC_DFP\1.10.146\atdf\PIC32MK1024MCF100.atdf
